.PHONY: clean All

All:
	@echo "----------Building project:[ TestDataType - Debug ]----------"
	@cd "TestDataType" && "$(MAKE)" -f  "TestDataType.mk"
clean:
	@echo "----------Cleaning project:[ TestDataType - Debug ]----------"
	@cd "TestDataType" && "$(MAKE)" -f  "TestDataType.mk" clean
